In [7]:
import numpy as np

In [9]:
a = np.array([1,5,6])
print(a)

[1 5 6]


In [10]:
a2arry = np.array(([1,2,3],[2,3,4]))
print(a2arry)

[[1 2 3]
 [2 3 4]]


In [12]:
print(a2arry+5)

[[6 7 8]
 [7 8 9]]


In [14]:
i = 0
for x in range(1,10+1):
    i+=x
    print(i)

1
3
6
10
15
21
28
36
45
55
